### ISSUE TITLE
OS X

### ISSUE THREAD

**Issue by alejoduque** [H-s-O/Kodtrol#22]
Hello, I have managed to compile under OS X but, although im giving the correct device address it doesnt seem to load or control my LM108 robot head LED Lamp. I can only see this error on the console:

> Kodtrol@0.0.1 start /Users/a/Documents/Kodtrol
> npx electron -r babel-register .

Attempted to load extension "React Developer Tools" that has already been loaded.
Attempted to load extension "Redux DevTools" that has already been loaded.
updateOutputs
updateInputs
updateDevices
Compiling script 1g8ol19ero0m 1
updateScripts
updateMedias
updateTimelines
updateBoards
DMX output
/Users/a/Documents/Kodtrol/src/renderer/Renderer.js:444
      obj[input.id] = input.inputInstance.refreshAndGetStatus();
                                          ^

TypeError: Cannot read property 'refreshAndGetStatus' of null
    at /Users/a/Documents/Kodtrol/src/renderer/Renderer.js:381:45
    at Array.reduce (<anonymous>)
    at Timeout.Renderer.updateIOStatus [as _onTimeout] (/Users/a/Documents/Kodtrol/src/renderer/Renderer.js:380:37)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)

Please let me know how to get more meaningful information and thanks in advance for any help.

**Comment by H-s-O** [comment]
Hi @alejoduque, from the error log I can see that you built the `develop` branch; however the current and most recent development branch (until merge) is [the-big-refactor](https://github.com/H-s-O/Kodtrol/tree/the-big-refactor). Can you please build with the `the-big-refactor` branch and see if the error still occurs?

P.S.: congrats on being the first third-party user to open an issue :)

**Comment by alejoduque** [comment]
no luck either, the window remains empty grey after creating a new project and i get this in the console.

^C(base) dspstv:Kodtrol a$ npm start

> Kodtrol@0.0.1 start /Users/a/Documents/bigrefractor/Kodtrol
> npx electron -r babel-register .

objc[69196]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffa75673d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11ad1ff50). One of the two will be used. Which one is undefined.
Attempted to load extension "React Developer Tools" that has already been loaded.
Attempted to load extension "Redux DevTools" that has already been loaded.
updateOutputs
updateInputs
updateDevices
updateScripts
updateMedias
updateTimelines
updateBoards

im launching things as stated on the readme:

npm run dev and then from another terminal npm start

**Comment by H-s-O** [comment]
From your output log, you seem to still be on the `develop` branch somehow (from the `> Kodtrol@0.0.1` log; the `the-big-refactor` would log `> kodtrol@0.1.0`).

Are you using `git` to clone the repository? Or are you downloading a zip archive from the "Download ZIP" feature of GitHub?

**Comment by alejoduque** [comment]
im cloning from the big refractor branch and launching as mentioned on the readme.

**Comment by H-s-O** [comment]
Can you post the result of the command `git branch` ran in your local clone of the repository?

**Comment by alejoduque** [comment]
dspstv:Kodtrol a$ git branch
* develop

indeed! now if i cloned this way:

git clone https://github.com/H-s-O/Kodtrol.git

and then moved to the Kodtrol dir.. how did i manage to change branches? perhaps i did that before when struggling to change the python version..

**Comment by H-s-O** [comment]
Once you've `cd` into the repository's directory, run:
```
git checkout the-big-refactor
git pull
```
That will switch your local repository to the correct branch.

**Comment by alejoduque** [comment]
Finally got it running under OS X 10.14 (Mojave) thanks for your kind help and software. I only have 2 robot heads LM108 from Big Dipper and even thouhj i have added the device Enttec DMXUSB Pro I dont seem to be able to address them correclty. Are there simple examples or a video tutorial on how to get the "hello lights" message going?

**Comment by H-s-O** [comment]
Sadly, I've not taken the time yet to do a "quick start" or tutorials for Kodtrol. At a minimum, there's the recently updated [manual](http://kodtrol.com/manual) on the website.

But we can try at least the following:
Assuming you have a similarly configured output for your Enttec DMXUSB Pro:
<img width="897" alt="Capture d’écran, le 2022-04-10 à 12 35 02" src="https://user-images.githubusercontent.com/17039502/162630451-622b720b-bfb1-4f46-9a9d-94a4ae74c2eb.png">
(Hint: after the output is added, you shoud see the status LED on the DMXUSB Pro blink, confirming that it's receiving data from Kodtrol.)

Assuming you have the following Device added to your device list (based on the manual I found [here](https://www.manualslib.com/manual/968746/Big-Dipper-Lm108.html?page=4#manual); also make sure to use the proper address you set on your fixture):
<img width="591" alt="Capture d’écran, le 2022-04-10 à 12 40 20" src="https://user-images.githubusercontent.com/17039502/162630494-9e4a7607-1e20-4d08-9f8d-8d0a810f7315.png">

And assuming you created a Script with the following config:
<img width="593" alt="Capture d’écran, le 2022-04-10 à 12 40 45" src="https://user-images.githubusercontent.com/17039502/162630506-0c0fbfb1-06b8-438f-a7ee-341e8f12a693.png">
and the following script content:
```
function frame(devices) {
  devices.forEach((device) => {
    device
      .setDim(map(Math.sin(Date.now() / 1000), -1, 1, 0, 255))
      .setRDim(255)
      .setGDim(255)
      .setBDim(255)
      .setWDim(255)
  })
}
```

Then if you click the "eye" icon next to the script name in the Scripts browser, you should see your light fixture do a slow fadein-fadeout animation.

**Comment by alejoduque** [comment]
Ohh wao, That is very generous from your part, be sure I will help you create documentation as soon as I get myself going with it all. Muchas gracias de verdad. :)

**Comment by H-s-O** [comment]
¡De nada!

Hope you got it working!

**Comment by alejoduque** [comment]
I have just done it! Light slowly dims up and down. Feels like i just crossed to the other shore. Merci bien!
